zuul:
  routes:
    micro-product:
      retryable: false #关闭重试
      path: /proudct/**   #指定路由path
      serviceId: micro-product #指定路由哪个服务名称
      sensitive-headers: #针对某个服务传输指定的headers信息 ，默认是过滤掉 Cookie,Set-Cookie,Authorization 这三个信息的,这里置空就是没有敏感数据，不要过滤掉这三个
  ignored-services: eureka-server #指定哪些服务不被zuul代理（多个使用逗号分隔）
  ignored-patterns: /**/local/**  #通配方式配置排除网关代理路径。所有符合ignored-patterns的请求路径都不被zuul网关代理。
  add-host-header: true        #添加host头信息，标识最初的服务端请求地址
  add-proxy-headers: true       #默认添加  X-Forwarded-*头域
  retryable: false  #全局关闭重试
