#zuul配置放在config server中动态路由
# 使用路径方式匹配路由规则。
# 参数key结构： zuul.routes.customName.path=xxx
# 用于配置路径匹配规则。
# 其中customName自定义。通常使用要调用的服务名称，方便后期管理
# 可使用的通配符有： * ** ?
# ? 单个字符
# * 任意多个字符，不包含多级路径
# ** 任意多个字符，包含多级路径
zuul:
  routes:
    micro-product:
      retryable: false #关闭重试
      path: /proudct/**   #指定路由path
      serviceId: micro-product #指定路由哪个服务名称
      sensitive-headers: #针对某个服务传输指定的headers信息 ，默认是过滤掉 Cookie,Set-Cookie,Authorization 这三个信息的,这里置空就是没有敏感数据，不要过滤掉这三个
    zuul-server:
      path: /local/**
      url: forward:/local      #url用于配置符合path的请求路径路由到的服务地址。
    blog:
      path: /blog/**
      url: http://localhost:8003/  #url用于配置符合path的请求路径路由到的服务地址。
    test:
      path: /test/**
      url: http://localhost:8099/  #url用于配置符合path的请求路径路由到的服务地址。  
  ignored-services: eureka-application-service #指定哪些服务不被zuul代理（多个使用逗号分隔）
#  ignored-services: * # 此方式相当于给所有新发现的服务默认排除zuul网关访问方式，只有配置了路由网关的服务才可以通过zuul网关访问
  ignored-patterns: /**/local/**  #通配方式配置排除网关代理路径。所有符合ignored-patterns的请求路径都不被zuul网关代理。
  prefix: /api                 # 配置请求路径前缀，所有基于此前缀的请求都由zuul网关提供代理。
  add-host-header: true        #添加host头信息，标识最初的服务端请求地址
  add-proxy-headers: true       #默认添加  X-Forwarded-*头域
  retryable: false  #全局关闭重试

#查看所有路由地址：http://localhost:9080/actuator/routes
